In [8]:
import os

# Imprimir el directorio de trabajo actual
print("Directorio actual:", os.getcwd())

# Listar qué archivos ve Python en la carpeta actual
print("Archivos aquí:", os.listdir('.'))

Directorio actual: c:\Users\Usuario\OneDrive\Desktop\Workshop1\notebooks
Archivos aquí: ['data_profiling.ipynb']

In [9]:
import os
import pandas as pd
import numpy as np

# Definir la ruta relativa desde la carpeta notebooks
file_path = '../data/raw/candidates.csv'

# Verificar si el archivo existe físicamente
if os.path.exists(file_path):
    print("¡Archivo encontrado con éxito!")
    df = pd.read_csv(file_path)
    print(f"Dimensiones del dataset: {df.shape[0]} filas y {df.shape[1]} columnas\n")
    display(df.head())
else:
    print(f"El archivo no se encuentra en: {os.path.abspath(file_path)}")
    print("Contenido del directorio superior (Workshop1):", os.listdir('..'))

El archivo no se encuentra en: c:\Users\Usuario\OneDrive\Desktop\Workshop1\data\raw\candidates.csv
Contenido del directorio superior (Workshop1): ['data', 'database', 'diagrams', 'notebooks', 'README.md', 'results', 'sql', 'src']

In [10]:
import os

data_path = '../data'

print("Contenido de la carpeta 'data':")
if os.path.exists(data_path):
    print(os.listdir(data_path))
    
    # Revisar si existe 'raw' adentro
    raw_path = os.path.join(data_path, 'raw')
    if os.path.exists(raw_path):
        print("\nContenido de la carpeta 'data/raw':")
        print(os.listdir(raw_path))
    else:
        print("\nLa subcarpeta 'raw' NO existe dentro de 'data'.")
else:
    print("La carpeta 'data' NO existe.")

Contenido de la carpeta 'data':
['candidates.csv', 'raw']

Contenido de la carpeta 'data/raw':
[]

In [12]:
import pandas as pd
import numpy as np

# Cargar el dataset especificando el separador ';'
file_path = '../data/raw/candidates.csv'
df = pd.read_csv(file_path, sep=';')

# Mostrar las verdaderas dimensiones del dataset
print(f"Dimensiones correctas del dataset: {df.shape[0]} filas y {df.shape[1]} columnas\n")

# Mostrar las primeras 5 filas para verificar la estructura
df.head()

Dimensiones correctas del dataset: 50000 filas y 10 columnas

,First Name,Last Name,Email,Application Date,Country,YOE,Seniority,Technology,Code Challenge Score,Technical Interview Score
0,Bernadette,Langworth,leonard91@yahoo.com,2021-02-26,Norway,2,Intern,Data Engineer,3,3
1,Camryn,Reynolds,zelda56@hotmail.com,2021-09-09,Panama,10,Intern,Data Engineer,2,10
2,Larue,Spinka,okey_schultz41@gmail.com,2020-04-14,Belarus,4,Mid-Level,Client Success,10,9
3,Arch,Spinka,elvera_kulas@yahoo.com,2020-10-01,Eritrea,25,Trainee,QA Manual,7,1
4,Larue,Altenwerth,minnie.gislason@gmail.com,2020-05-20,Myanmar,13,Mid-Level,Social Media Community Management,9,7

In [13]:
# 1. Información de tipos de datos y valores no nulos
print("=== INFORMACIÓN GENERAL Y TIPOS DE DATOS ===")
df.info()

print("\n" + "="*50 + "\n")

# 2. Conteo de valores nulos por columna
print("=== VALORES NULOS POR COLUMNA ===")
print(df.isnull().sum())

print("\n" + "="*50 + "\n")

# 3. Conteo de registros duplicados exactos
print("=== REGISTROS DUPLICADOS ===")
print(f"Filas duplicadas encontradas: {df.duplicated().sum()}")

=== INFORMACIÓN GENERAL Y TIPOS DE DATOS ===
<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   First Name                 50000 non-null  str
 1   Last Name                  50000 non-null  str
 2   Email                      50000 non-null  str
 3   Application Date           50000 non-null  str
 4   Country                    50000 non-null  str
 5   YOE                        50000 non-null  int64
 6   Seniority                  50000 non-null  str
 7   Technology                 50000 non-null  str
 8   Code Challenge Score       50000 non-null  int64
 9   Technical Interview Score  50000 non-null  int64
dtypes: int64(3), str(7)
memory usage: 3.8 MB

==================================================

=== VALORES NULOS POR COLUMNA ===
First Name                   0
Last Name                    0
Email                        0
Application Date             0
Country                      0
YOE                          0
Seniority                    0
Technology                   0
Code Challenge Score         0
Technical Interview Score    0
dtype: int64

==================================================

=== REGISTROS DUPLICADOS ===
Filas duplicadas encontradas: 0

In [14]:
# Estadísticas de YOE, Code Challenge Score y Technical Interview Score
print("=== ESTADÍSTICAS DESCRIPTIVAS ===")
df[['YOE', 'Code Challenge Score', 'Technical Interview Score']].describe()

=== ESTADÍSTICAS DESCRIPTIVAS ===

                YOE  Code Challenge Score  Technical Interview Score
count  50000.000000          50000.000000               50000.000000
mean      15.286980              4.996400                   5.003880
std        8.830652              3.166896                   3.165082
min        0.000000              0.000000                   0.000000
25%        8.000000              2.000000                   2.000000
50%       15.000000              5.000000                   5.000000
75%       23.000000              8.000000                   8.000000
max       30.000000             10.000000                  10.000000

In [15]:
# 1. Rangos de los puntajes de evaluación y experiencia
print("=== RANGOS NUMÉRICOS (MIN Y MAX) ===")
display(df[['YOE', 'Code Challenge Score', 'Technical Interview Score']].describe())

print("\n" + "="*50 + "\n")

# 2. Conteo de Candidatos Contratados vs No Contratados según Regla de Negocio
# HIRED = Code Challenge Score >= 7 AND Technical Interview Score >= 7
hired_count = df[(df['Code Challenge Score'] >= 7) & (df['Technical Interview Score'] >= 7)].shape[0]
not_hired_count = len(df) - hired_count

print("=== EVALUACIÓN REGLA DE NEGOCIO (HIRED / NOT HIRED) ===")
print(f"Candidatos contratados (HIRED): {hired_count} ({hired_count/len(df)*100:.2f}%)")
print(f"Candidatos no contratados (NOT HIRED): {not_hired_count} ({not_hired_count/len(df)*100:.2f}%)")

print("\n" + "="*50 + "\n")

# 3. Valores únicos por variables categóricas principales
print("=== VALORES ÚNICOS CATEGÓRICOS ===")
print(f"Cantidad de Países distintos: {df['Country'].nunique()}")
print(f"Niveles de Seniority: {df['Seniority'].unique().tolist()}")
print(f"Cantidad de Tecnologías distintas: {df['Technology'].nunique()}")

=== RANGOS NUMÉRICOS (MIN Y MAX) ===

                YOE  Code Challenge Score  Technical Interview Score
count  50000.000000          50000.000000               50000.000000
mean      15.286980              4.996400                   5.003880
std        8.830652              3.166896                   3.165082
min        0.000000              0.000000                   0.000000
25%        8.000000              2.000000                   2.000000
50%       15.000000              5.000000                   5.000000
75%       23.000000              8.000000                   8.000000
max       30.000000             10.000000                  10.000000

==================================================

=== EVALUACIÓN REGLA DE NEGOCIO (HIRED / NOT HIRED) ===
Candidatos contratados (HIRED): 6698 (13.40%)
Candidatos no contratados (NOT HIRED): 43302 (86.60%)

==================================================

=== VALORES ÚNICOS CATEGÓRICOS ===
Cantidad de Países distintos: 244
Niveles de Seniority: ['Intern', 'Mid-Level', 'Trainee', 'Junior', 'Lead', 'Architect', 'Senior']
Cantidad de Tecnologías distintas: 24

In [16]:
# Exportar métricas generales a un informe rápido
profiling_summary = pd.DataFrame({
    'Metric': [
        'Total Records', 
        'Total Columns', 
        'Duplicate Rows', 
        'Hired Candidates', 
        'Hired Ratio (%)',
        'Unique Countries',
        'Unique Technologies'
    ],
    'Value': [
        len(df), 
        df.shape[1], 
        df.duplicated().sum(), 
        hired_count, 
        round(hired_count / len(df) * 100, 2),
        df['Country'].nunique(),
        df['Technology'].nunique()
    ]
})

print("=== RESUMEN EJECUTIVO DE PROFILING ===")
display(profiling_summary)

=== RESUMEN EJECUTIVO DE PROFILING ===

                Metric    Value
0        Total Records  50000.0
1        Total Columns     10.0
2       Duplicate Rows      0.0
3     Hired Candidates   6698.0
4      Hired Ratio (%)     13.4
5     Unique Countries    244.0
6  Unique Technologies     24.0